services:
  primary:
    build:
      context: .
      dockerfile: ./apps/primary/Dockerfile
      target: development
    command: yarn start:dev primary
    env_file:
      - ./apps/primary/.env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_master_data:/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_USER=admin
      - MONGO_INITDB_PASSWORD=admin
    restart: always

volumes:
  mongodb_master_data:
    driver: local
